name:           L&P Hosting Blog
description:    Official blog for L&P Hosting.
url:            http://blog.landphosting.com

markdown:       kramdown
highlighter:    pygments
permalink:      pretty
paginate:       5
encoding:       UTF-8

exclude:        ["README.md"]
